(deftheme Dark
  "Created 2012-06-27.")

(custom-theme-set-faces
 'Dark
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "#666" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 160 :width normal :foundry "apple" :family "Menlo"))))
 '(cursor ((t (:background "#888"))))
 '(fixed-pitch ((t (:weight bold :family "Monospace"))))
 '(variable-pitch ((t nil)))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#555"))))
 '(highlight ((t (:background "#241882" :foreground "#70DBDB"))))
 '(region ((t (:background "#008B8B" :foreground "#0ff"))))
 '(shadow ((t (:foreground "#333"))))
 '(secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#ffaa00"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "Red"))))
 '(font-lock-constant-face ((t (:foreground "#00ff00"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#4186be"))))
 '(font-lock-keyword-face ((t (:foreground "#00ffff"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#ffff00"))))
 '(font-lock-type-face ((t (:foreground "Coral"))))
 '(font-lock-variable-name-face ((t (:foreground "White" :weight bold))))
 '(font-lock-warning-face ((t (:foreground "Red" :weight bold))))
 '(button ((t (:weight bold :inherit link))))
 '(link ((t (:underline t :foreground "cyan"))))
 '(link-visited ((t (:underline t :foreground "dark cyan" :inherit (link)))))
 '(fringe ((t (:background "#333" :foreground "#000"))))
 '(header-line ((t (:background "#333" :foreground "#000" :box nil))))
 '(tooltip ((t (:background "#111" :foreground "#777"))))
 '(mode-line ((t (:background "#111" :foreground "#444" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:foreground "#444" :weight bold))))
 '(mode-line-emphasis ((t (:foreground "#bbb" :weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:inherit mode-line :background "Black" :foreground "#444" :box (:line-width -1 :color "grey40") :weight light))))
 '(isearch ((t (:background "Red" :foreground "pink"))))
 '(isearch-fail ((t (:background "pink" :foreground "Red"))))
 '(lazy-highlight ((t (:foreground "Red"))))
 '(match ((t (:background "lightslateblue" :foreground "White"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'Dark)
