;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        cperl-electric-paren
        cperl-electric-rparen
        cua-copy-region
        cua-cut-region
        cua-paste
        electric-newline-and-maybe-indent
        helm-all-mark-rings
        helm-mini
        indent-for-tab-command
        isearch-abort
        isearch-backward-regexp
        isearch-exit
        isearch-forward-regexp
        isearch-printing-char
        kmacro-end-or-call-macro
        markdown-outdent-or-delete
        nxml-electric-slash
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-open-line
        org-self-insert-command
        org-shiftleft
        org-shiftright
        org-yank
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-kill
        paredit-meta-doublequote
        paredit-open-round
        paredit-open-square
        paredit-splice-sexp
        set-fill-column
        sh-assignment
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        wdired-finish-edit
        swiper
        wdired-next-line
        wdired-previous-line
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        comment-dwim
        dired-toggle-read-only
        diredp-delete-this-file
        iedit-switch-to-mc-mode
        kmacro-start-macro-or-insert-counter
        mark-whole-buffer
        markdown-exdent-or-delete
        ))
