;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-copy-region
        org-beginning-of-line
        org-self-insert-command
        org-yank
        paredit-forward-delete
        ))

(setq mc/cmds-to-run-once
      '(
        ))
