;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        cua-copy-region
        cua-paste
        helm-mini
        isearch-abort
        isearch-exit
        isearch-forward-regexp
        isearch-printing-char
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        paredit-forward-delete
        paredit-kill
        paredit-open-round
        ))

(setq mc/cmds-to-run-once
      '(
        ))
